Upload Coverall report even if some tests fail

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -5,13 +5,12 @@ name: Node.js CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -19,17 +18,24 @@ jobs:
         node-version: [18.x, 20.x, 22.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
-
     steps:
       - uses: actions/checkout@v4
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
-          cache: 'npm'
+          cache: "npm"
       - run: npm ci
       - run: npm run build --if-present
-      - run: npm test
+
+      - name: Run tests
+        id: tests
+        run: |
+          npm test || echo "failed=true" >> $GITHUB_OUTPUT
 
       - name: Coveralls GitHub Action
         uses: coverallsapp/github-action@v2.3.6
+
+      - name: Fail if tests failed
+        if: steps.tests.outputs.failed == 'true'
+        run: exit 1
